길이가 10인 배열을 생성하고, 배열의 크기(shape), 차원(ndim), 데이터 타입(dtype), 전체 크기(nbytes)를 출력

In [44]:
import numpy as np

In [45]:
arr1 = np.array(10)
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.nbytes)


()
0
int64
8


값이 5로 채워진 3x4 배열을 생성

In [46]:
arr2 = np.full((3, 4), 5)
arr2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

0에서 50까지의 정수를 가지는 1D 배열을 생성하고, 그 배열을 5x10 형태로 재구성하세요


In [47]:
arr3 = np.arange(1,51)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [48]:
reshaped_arr = arr3.reshape(5, 10)
reshaped_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

두 개의 2x2 배열 A = [[1, 2], [3, 4]]와 B = [[5, 6], [7, 8]]를 생성하고 
행렬 덧셈
행렬 요소별 곱셈

In [49]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [50]:
A + B


array([[ 6,  8],
       [10, 12]])

In [51]:
A * B

array([[ 5, 12],
       [21, 32]])

배열 [1, 2, 3, 4, 5, 6, 7, 8, 9]에서 짝수만 선택하세요.

In [52]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
even_number = arr4[arr4 % 2 == 0]
even_number

array([2, 4, 6, 8])

배열 [10, 20, 30, 40, 50]에서 30보다 큰 값을 모두 0으로 변경하세요.

In [53]:
arr5 = np.array([10,20,30,40,50,])
big_arr = arr5[arr5 > 30] = 0
arr5

array([10, 20, 30,  0,  0])

3x3 배열  임의 값 들어간 것을 생성하고, 배열의 최댓값, 최솟값, 평균, 표준 편차를 구하세요.

In [54]:
arr6 = np.random.randint(1, 10, size=(3, 3))
arr6

array([[6, 1, 3],
       [1, 2, 1],
       [6, 1, 3]])

In [55]:
max_value = arr6.max()
min_value = arr6.min()
mean_value = arr6.mean()
std_deviation = arr6.std()

print(max_value)
print(min_value)
print(mean_value)
print(std_deviation)

6
1
2.6666666666666665
1.9436506316151


각 행의 최댓값, 최솟값, 평균, 합계를 구하세요

In [56]:
max_value + min_value + mean_value + std_deviation

11.610317298281766

5x5 배열을 생성하고, 배열에서 짝수 값만 선택하세요.

In [57]:
arr7 = np.random.randint(1, 10, size=(5, 5))
arr7

array([[3, 7, 7, 8, 3],
       [3, 8, 3, 5, 7],
       [3, 3, 1, 3, 7],
       [4, 3, 6, 7, 4],
       [4, 4, 2, 3, 2]])

In [58]:
even_number = arr7[arr7 % 2 == 0]
arr7

array([[3, 7, 7, 8, 3],
       [3, 8, 3, 5, 7],
       [3, 3, 1, 3, 7],
       [4, 3, 6, 7, 4],
       [4, 4, 2, 3, 2]])

배열 [1, 4, 9, 16, 25]의 각 요소에 대해 제곱근을 계산하세요.

In [61]:
arr8 = np.array([1, 4, 9, 16, 25])
sqrt_arr = np.sqrt(arr8)
sqrt_arr

array([1., 2., 3., 4., 5.])