### 기본 사칙 연산

In [69]:
import numpy as np

In [70]:
data_list_first = [1, 2, 3]
type(data_list_first), len(data_list_first)

(list, 3)

In [71]:
data_list_second = [4,5,6]

In [72]:
data_list_first + data_list_second

[1, 2, 3, 4, 5, 6]

In [73]:
data_array_first = np.array(data_list_first)
type(data_array_first), len(data_array_first)

(numpy.ndarray, 3)

In [74]:
data_array_second = np.array(data_list_second)

In [75]:
data_array_first + data_array_second

array([5, 7, 9])

In [76]:
data_list_third = [-1, 2, -3]

In [77]:
data_array_first / data_array_second

array([0.25, 0.4 , 0.5 ])

In [78]:
data_array_first * data_array_second

array([ 4, 10, 18])

In [79]:
data_array_third = np.array(data_list_third)

In [80]:
data_array_first - data_list_third, data_list_third - data_array_first

(array([2, 0, 6]), array([-2,  0, -6]))

### array 연산

In [81]:
data_list_third * 2

[-1, 2, -3, -1, 2, -3]

In [82]:
data_array_third * 2  # [-2, 0, -6] * [2, 2, 2]

array([-2,  4, -6])

### 조건절 적용

In [83]:
cond_array_first = np.array([10, 20, 30])

In [84]:
cond_array_first > 10

array([False,  True,  True])

In [85]:
conditions = cond_array_first[cond_array_first > 10]
conditions

array([20, 30])

In [86]:
cond_array_first[conditions]

IndexError: index 20 is out of bounds for axis 0 with size 3

In [36]:
conditions.all()

True

In [37]:
cond_array_second = np.array([20, 20, 30])
conditions_second = cond_array_second > 20
conditions_second

array([False, False,  True])

In [38]:
conditions_second.all()

False

In [40]:
conditions_second.any() #구성 요소 중 하나라도 True -> True

True

In [41]:
# [10, 20, 30] -> 10 초과, 30 미만
conditions_third = (cond_array_first > 10) & (cond_array_first < 30)
conditions_third

array([False,  True, False])

In [42]:
cond_array_first[conditions_third]

array([20])

### 집계함수

In [44]:
aggregation_list_first = [
                         [1, 2]       
                        ,[3, 4]
                        ,[5, 6]
                        ,[7, 8]
                        ]       #row 4, column 2

In [45]:
aggregation_array_first = np.array(aggregation_list_first)
aggregation_array_first

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [55]:
#aggregation_array_first.sum()
#aggregation_array_first.sum(axis=0) #행 중심
aggregation_array_first.sum(axis=1)  #열 중심

array([ 3,  7, 11, 15])

### max() min(), mean()

In [98]:
#aggregation_array_first.max()
aggregation_array_first.max(axis=0)

array([7, 8])

In [97]:
aggregation_array_first.argmax(axis=0)

array([3, 3])

### 특수 행렬 생성

In [51]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬 정보 확인

In [56]:
aggregation_array_first.shape, #차원 크기

((4, 2),)

In [58]:
aggregation_array_first.ndim#차원 수

2

In [59]:
aggregation_array_first.dtype

dtype('int64')

In [88]:
aggregation_array_first.size        #행열의 개수 합한거

8

In [89]:
aggregation_array_first.nbytes, aggregation_array_first.itemsize * aggregation_array_first.size #요소에 전체 바이트 사이즈

(64, 64)

In [ ]:
array_float = aggregation_array_first.astype(np.float128)

In [93]:
array_float.shape, array_float.dtype, array_float.nbytes        #AI원자화에 이용

((4, 2), dtype('float128'), 128)